// Generate docs/GAS-REPORT.md from test/vectors/*.json against a deployed
// StarkVerifier + StarkVerifierGasMeter pair.
//
// Usage:
//   STARK_CONFIG=config/local-stark.json npm run gas:report [-- --all] [--vectors <dir>] [--out <file>]
//
// Every vector goes through the verify-proof logic (qrl_call of verify, then
// the verifyAndLog transaction). Mutated vectors (expected.valid === false)
// are skipped unless --all is given. The report is regenerated in full; keep
// the structure stable because docs/L2-ARCHITECTURE.md reads from it.

const fs = require('fs');
const path = require('path');

require('dotenv').config({ path: path.join(__dirname, '..', '.env'), quiet: true });

const { RpcClient } = require('./lib/rpc');
const { getSender } = require('./lib/devAccount');
const { loadConfig, resolveConfigPath } = require('./deploy');
const { loadVector, runVerifyProof } = require('./verify-proof');

const repoRoot = path.join(__dirname, '..');
const defaultVectorsDir = path.join(repoRoot, 'test', 'vectors');
const defaultOutFile = path.join(repoRoot, 'docs', 'GAS-REPORT.md');

function parseArgs(argv) {
  const options = { all: false, vectorsDir: defaultVectorsDir, outFile: defaultOutFile };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = () => {
      if (i + 1 >= argv.length) throw new Error(`${arg} needs a value`);
      i += 1;
      return argv[i];
    };
    if (arg === '--all') options.all = true;
    else if (arg === '--vectors') options.vectorsDir = path.resolve(repoRoot, next());
    else if (arg === '--out') options.outFile = path.resolve(repoRoot, next());
    else if (arg === '--config') options.config = path.resolve(repoRoot, next());
    else throw new Error(`unknown option ${arg}`);
  }
  return options;
}

function listVectorFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => path.join(dir, name));
}

function cell(value) {
  if (value === null || value === undefined) return '?';
  return String(value);
}

function renderReport({ config, chainId, manifest, rows, generatedAt, skipped }) {
  const lines = [];
  lines.push('# Gas report');
  lines.push('');
  lines.push('Generated by `npm run gas:report`; do not edit by hand.');
  lines.push('');
  lines.push(`- Generated at: ${generatedAt}`);
  lines.push(`- Network: ${config.network ?? 'unknown'} (chain ${chainId})`);
  lines.push(`- Compiler: ${manifest?.compilerVersion ?? config.compilerVersion ?? 'unknown'}`);
  lines.push(`- Plonky3: ${manifest?.plonky3Version ?? config.plonky3Version ?? 'unknown'}`);
  lines.push(`- StarkVerifier: ${config.contracts?.StarkVerifier ?? 'not deployed'}`);
  lines.push(
    `- StarkVerifierGasMeter: ${config.contracts?.StarkVerifierGasMeter ?? 'not deployed'}`
  );
  lines.push('- Block gas cap: 20000000 (consensus); target per verification: 8000000 or less');
  lines.push('');
  lines.push(
    'Columns: `estimateGas` is the node estimate for the `verifyAndLog` transaction, `gasUsed` is the receipt value (calldata + meter + verifier), `inner gas` is the `gasleft()` delta around the STATICCALL as reported by the `Verified` event.'
  );
  lines.push('');
  lines.push(
    '| Vector | Config | degreeBits | Proof bytes | estimateGas | gasUsed | inner gas | verify ok |'
  );
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const row of rows) {
    lines.push(
      `| ${row.vector} | ${cell(row.config)} | ${cell(row.degreeBits)} | ${row.proofBytes} | ` +
        `${cell(row.estimateGas)} | ${cell(row.gasUsed)} | ${cell(row.innerGas)} | ${cell(row.ok)} |`
    );
  }
  if (rows.length === 0) {
    lines.push('| (no vectors) | | | | | | | |');
    lines.push('');
    lines.push('No vectors were found. Generate them with `npm run prover:vectors`.');
  }
  if (skipped.length > 0) {
    lines.push('');
    lines.push(
      `Skipped ${skipped.length} mutated vector(s) (expected.valid is false); rerun with \`--all\` to include them: ${skipped.join(', ')}.`
    );
  }
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const configPath = options.config || resolveConfigPath(process.env);
  const config = loadConfig(configPath);
  const manifestPath = path.join(repoRoot, 'build', 'hyperion', 'manifest.json');
  const manifest = fs.existsSync(manifestPath)
    ? JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
    : null;

  const rpc = new RpcClient(config.rpcUrl);
  const chainId = await rpc.chainId();
  if (chainId !== Number(config.chainId)) {
    throw new Error(`chainId mismatch: expected ${config.chainId}, got ${chainId}`);
  }
  const sender = await getSender(rpc, { repoRoot, chainId });

  const rows = [];
  const skipped = [];
  for (const file of listVectorFiles(options.vectorsDir)) {
    const vector = loadVector(file);
    if (!options.all && vector.expected && vector.expected.valid === false) {
      skipped.push(vector.name);
      continue;
    }
    console.log(`verifying ${vector.name} (${vector.proof.length} bytes)...`);
    let result;
    try {
      result = await runVerifyProof({ rpc, sender, config, vector });
    } catch (error) {
      console.error(`  failed: ${error.message}`);
      rows.push({
        vector: vector.name,
        config: vector.config,
        degreeBits: vector.degreeBits,
        proofBytes: vector.proof.length,
        estimateGas: 'error',
        gasUsed: 'error',
        innerGas: null,
        ok: false,
      });
      continue;
    }
    const row = {
      vector: vector.name,
      config: vector.config,
      degreeBits: vector.degreeBits,
      proofBytes: result.proofBytes,
      estimateGas: result.tx?.estimateGas ?? null,
      gasUsed: result.tx?.gasUsed ?? null,
      innerGas: result.tx?.verified?.gasUsed ?? null,
      ok: result.tx?.verified?.ok ?? result.call.ok,
    };
    console.log(
      `  estimate ${cell(row.estimateGas)}, used ${cell(row.gasUsed)}, inner ${cell(row.innerGas)}, ok ${row.ok}`
    );
    rows.push(row);
  }

  const report = renderReport({
    config,
    chainId,
    manifest,
    rows,
    generatedAt: new Date().toISOString(),
    skipped,
  });
  fs.mkdirSync(path.dirname(options.outFile), { recursive: true });
  fs.writeFileSync(options.outFile, report);
  console.log(`\nWrote ${options.outFile} (${rows.length} row(s))`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error('\ngas:report failed:', err.message);
    if (err.data) console.error('Data:', err.data);
    process.exit(1);
  });
}

module.exports = { listVectorFiles, parseArgs, renderReport };
